### ISSUE TITLE
ShipmentState & PaymentState should be optional / nullable on Order

### ISSUE THREAD

**Issue by edwardschipper** [commercetools/commercetools-dotnet-core-sdk#101]
The [API documentation on order](https://docs.commercetools.com/http-api-projects-orders#order) specifies that the shipmentState & paymentState are optional attributes on an order.
But in the current version of the SDK the corresponding fields (type=enum) on the order model are not nullable.
This results in a default value of ShipmentState.Shipped and PaymentState.BalanceDue being set on orders where the shipmentState or paymentState is not set (yet). 

Let's make these fields nullable.

**Comment by jenschude** [comment]
Fix has been merged.

Thanks for the report
