### ISSUE TITLE
Where clause with "in" and arrays and lists creates a bad request

### ISSUE THREAD

**Issue by btastic** [commercetools/commercetools-dotnet-core-sdk#109]
Given the following test cases:

```
[Fact]
public void ExpressionWhereInString()
{
    string[] orderNumbers = { "5", "10", "15" };
    Expression<Func<Order, bool>> expression = x => x.OrderNumber.In(orderNumbers);
    IQueryPredicateExpressionVisitor queryPredicateExpressionVisitor = this.linqFixture.GetService<IQueryPredicateExpressionVisitor>();
    string result = queryPredicateExpressionVisitor.Render(expression);
    Assert.Equal("orderNumber in (\"5\", \"10\", \"15\")", result);
}
```
Outputs the following:
![image](https://user-images.githubusercontent.com/6894999/75780798-4f7a2200-5d5c-11ea-8242-04df45de3fdb.png)

```
[Fact]
public void ExpressionWhereInStringList()
{
    List<string> orderNumbers = new List<string>(){ "5", "10", "15" };
    Expression<Func<Order, bool>> expression = x => x.OrderNumber.In(orderNumbers.ToArray());
    IQueryPredicateExpressionVisitor queryPredicateExpressionVisitor = this.linqFixture.GetService<IQueryPredicateExpressionVisitor>();
    string result = queryPredicateExpressionVisitor.Render(expression);
    Assert.Equal("orderNumber in (\"5\", \"10\", \"15\")", result);
}
```
Outputs the following:
![image](https://user-images.githubusercontent.com/6894999/75780817-586af380-5d5c-11ea-8cc1-dac457f5747b.png)

From what I analyzed, it seems that the `ConstantPredicateVisitorConverter` is not the right job for arrays/collections. I tried implementing a `InMethodPredicateVisitorConverter` which seems to do a similar thing when filtering, but there are some bits that I don't know :/

If you need anything, shoot me an email @jenschude

**Comment by jenschude** [comment]
Very nice finding. Seems that we missed this use case and your reports are really helpful. Often it's a simple fix once we know about the issue.

**Comment by jenschude** [comment]
And btw. in the meantime you can always use build normal string without the fancy LINQ expression but this is only half the fun 😄

**Comment by btastic** [comment]
Yep, but thats a fair bit of code to rewrite. I will just wait for you :)

**Comment by jenschude** [comment]
For this special case it would be a one liner

```
var queryCommand = new QueryCommand<Order>();
List<string> orderNumbers = new List<string>(){ "5", "10", "15" };
queryCommand.Where($"orderNumber in (\"{string.Join("\",\"", orderNumbers)}\")");
queryCommand.Where(o => o.Country == "US");
```

You can mix pure strings with the expression when you call where multiple times. So later you would have to replace only the strings
