### ISSUE TITLE
Querying with datetimes does not have quotes / correct format

### ISSUE THREAD

**Issue by btastic** [commercetools/commercetools-dotnet-core-sdk#110]
Given the following test case:
```
[Fact]
public void ExpressionWithDateTimeFilters()
{
    DateTime startDate = new DateTime(2020, 11, 21);
    DateTime endDate = startDate.AddMonths(1);

    Expression<Func<Order, bool>> expression = x => x.CreatedAt >= startDate && x.CreatedAt <= endDate;
    IQueryPredicateExpressionVisitor queryPredicateExpressionVisitor = this.linqFixture.GetService<IQueryPredicateExpressionVisitor>();
    string result = queryPredicateExpressionVisitor.Render(expression);
    Assert.Equal("createdAt >= \"2020-11-21\" and createdAt <= \"2020-12-21\"", result);
}
```

Produces the following outcome:
![image](https://user-images.githubusercontent.com/6894999/75794097-9a059980-5d70-11ea-8520-4b03e1d123f1.png)

**Comment by jenschude** [comment]
Date, Times and DateTimes are a little bit more special, cause as in the Models we store them as DateTime but on the API side they may be a Date, Time or DateTime.

Therefor we have for the predicate expressions a `AsDateTimeAttribute`, `AsDateAttribute` and `AsTimeAttribute` extension method. They format it correctly so the API understands them.

**Comment by jenschude** [comment]
See also:

https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/commercetools.Sdk/Tests/commercetools.Sdk.Linq.Tests/QueryPredicateTests.cs#L297

https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/commercetools.Sdk/Tests/commercetools.Sdk.Linq.Tests/QueryPredicateTests.cs#L316

https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/commercetools.Sdk/Tests/commercetools.Sdk.Linq.Tests/QueryPredicateTests.cs#L344

**Comment by btastic** [comment]
I saw those tests but I thought it was special cases for attributes. I did not see any test cases which test filtering for dates (CreatedAt on orders) for example, which does not seem to work as expected.

**Comment by jenschude** [comment]
Just tried it with:

```
        [Fact]
        public void ExpressionPropertyDateTimeValueVariableEqual()
        {
            var cDateTime = DateTime.Parse("2019-09-11T15:27:55.123+02:00", CultureInfo.InvariantCulture, DateTimeStyles.AdjustToUniversal).ToLocalTime();
            Assert.Equal(DateTimeKind.Local, cDateTime.Kind);//local time

            Expression<Func<ProductProjection, bool>> expression = p => p.CreatedAt == cDateTime.AsDateTimeAttribute();
            IQueryPredicateExpressionVisitor queryPredicateExpressionVisitor = this.linqFixture.GetService<IQueryPredicateExpressionVisitor>();
            string result = queryPredicateExpressionVisitor.Render(expression);
            Assert.Equal("createdAt = \"2019-09-11T13:27:55.123Z\"", result);
        }

**Comment by jenschude** [comment]
Only thing arguable would be the naming as it's a bit misleading

**Comment by btastic** [comment]
The usage is also misleading. I would expect that something like this would just work:

```
    DateTime startDate = new DateTime(2020, 11, 21);
    DateTime endDate = startDate.AddMonths(1);

    Expression<Func<Order, bool>> expression = x => x.CreatedAt >= startDate && x.CreatedAt <= endDate;
```

**Comment by jenschude** [comment]
But in your test you printed it out as a Date. Where as the API expects a DateTime. So it's better to be more explicit how it should be written out than to have a wrong implicit value.

**Comment by btastic** [comment]
Ahh I see, yes. So it is depending on the resources field whether it is Date, Time or DateTime correct?

**Comment by jenschude** [comment]
Exactly :) And C# doesn't differentiate between them. So we have to be explicit in the predicates.

**Comment by btastic** [comment]
Hmm not a huge fan, but something I can deal with. Thanks for the explanaition. I think you should mention this in your documentation somewhere..

**Comment by jenschude** [comment]
You can find them here:

https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/PredicateExpressions.md

Also it's not explicitly stating that you can use them at any date or datetime field. We will add some examples and tests.

**Comment by jenschude** [comment]
We will also open the AsDate, AsTime and AsDateTime extension methods also for query predicate to have less misleading names.
