### ISSUE TITLE
OrderLine discountedPrice DTO mismatch

### ISSUE THREAD

**Issue by PepijnK** [commercetools/commercetools-dotnet-core-sdk#114]
hi,

I'm trying to find the `discountedPrice` property in the SDK OrderLine DTO from the following json response of GET: /order/{id}

```
{
    "type": "Order",
....
    "lineItems": [
            "price": {
                "value": {
                    "type": "centPrecision",
                    "currencyCode": "USD",
                    "centAmount": 999,
                    "fractionDigits": 2
                },
                "id": "[REDACTED]"
            },
            "quantity": 1,
            "discountedPrice": {
                "value": {
                    "type": "centPrecision",
                    "currencyCode": "USD",
                    "centAmount": 899,
                    "fractionDigits": 2
                },
                "includedDiscounts": [
                    {
                        "discount": {
                            "typeId": "cart-discount",
                            "id": "[REDACTED]"
                        },
                        "discountedAmount": {
                            "type": "centPrecision",
                            "currencyCode": "USD",
                            "centAmount": 100,
                            "fractionDigits": 2
                        }
                    }
                ]
            },
....
   ]
....
}
```

While the SDK DTO only provide Price:
```
public class LineItem
  {
...
    public Price Price { get; set; }

    public TaxedItemPrice TaxedPrice { get; set; }

    public Money TotalPrice { get; set; }

    public List<DiscountedLineItemPriceForQuantity> DiscountedPricePerQuantity { get; set; }
...
  }
```

Price does include a Discount, however this is not set because it doesn't fit the JSON format.

**Comment by MicheleRezk** [comment]
Hi,
Based on [Documentation](https://docs.commercetools.com/http-api-projects-carts#lineitem) 
you can find the discountedPrice property in the DiscountedPricePerQuantity Property, It's a list of DiscountedLineItemPriceForQuantity and each Item in this list has the DiscountedPrice Property like this:

"discountedPricePerQuantity": [
        {
          "quantity": 2,
          "discountedPrice": {
            "value": {
              "type": "centPrecision",
              "currencyCode": "EUR",
              "centAmount": 2256,
              "fractionDigits": 2
            },
            "includedDiscounts": [
              {
                "discount": {
                  "typeId": "cart-discount",
                  "id": "69850bb7-bac8-4927-b452-746bf1b1d8b5"
                },
                "discountedAmount": {
                  "type": "centPrecision",
                  "currencyCode": "EUR",
                  "centAmount": 323,
                  "fractionDigits": 2
                }
              }
            ]
          }
        }
      ]

Please let me know if this answers your questions

**Comment by jenschude** [comment]
The discountedPrice property has been deprecated. See here:

https://docs.commercetools.com/release-notes.html#12102015

**Comment by PepijnK** [comment]
so that means I have to calculate the discountedPrice? As `Price.Discounted.Value` is not set by the SDK.

**Comment by jenschude** [comment]
The `Price.Discounted.Value` comes from a product discount and not a cart discount.

And yes you have to calculate it. Sum up the discountedPrice multiplied by the quantity in discountedPricePerQuantity. You could do this also simply in an extension method targeting a LineItem for example.
