### ISSUE TITLE
Typo in price tiers cause returning default value

### ISSUE THREAD

**Issue by carlokok** [commercetools/commercetools-dotnet-core-sdk#117]
https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/HEAD/commercetools.Sdk/commercetools.Sdk.Domain/Products/PriceTier.cs 
has 
MinimumQuanity 
should be
MinimumQuantity 

This fixes the min quantity being 0 otherwise.

**Comment by jenschude** [comment]
Just fixed it. Thanks for the hint.
