### ISSUE TITLE
Query with Nested Custom Fields

### ISSUE THREAD

**Issue by jgnatenko** [commercetools/commercetools-dotnet-core-sdk#125]
Hi,

I have the following problem:

**Task**: get Customer, that has KupCustomerNumber nested in custom field Adresses->AdditionalAddressInfo (This is field contains custom Object).

**Solution:**
In **normal situation** for retrieving Customer we could use **lambda expression** like:
  command.Where(s => s.Addresses.Any(m => m.AdditionalAddressInfo.Contains("CustomerNo:" + customer.KuPCustomerNo + "\"")));

Could you please say me if that **possible** to do **with your current solution** like:
command.Where("custom(fields(Addresses(AdditionalAddressInfo(CustomerNo =\"" + customer.KuPCustomerNo + "\"))");

Thanks!

**Comment by jenschude** [comment]
This is not possible as the custom fields can't have nested fields.

**Comment by jgnatenko** [comment]
Thanks!
