### ISSUE TITLE
Missing InventoryEntryQuantitySet Message 

### ISSUE THREAD

**Issue by glennsdavis** [commercetools/commercetools-dotnet-core-sdk#127]
It appears SDK is missing class for InventoryEntryQuantitySet message. Per commercetools documentation:

**InventoryEntryQuantitySet Message**

This message is the result of the update InventoryEntry with AddQuantity, RemoveQuantity or ChangeQuantity update action. In addition to the common Message fields, the InventoryEntryQuantitySet message contains the following fields:

type - String - "InventoryEntryQuantitySet"
oldQuantityOnStock - Number
newQuantityOnStock - Number
oldAvailableQuantity - Number
newAvailableQuantity - Number

**Comment by MicheleRezk** [comment]
Just fixed it. Thanks for the hint.

**Comment by glennsdavis** [comment]
Michele, thank you for the quick response. Do you know when the next release of the SDK will be published to NuGet?

**Comment by jenschude** [comment]
Sorry for the late answer.

The master will be always build and published at myget. E.G.:

https://www.myget.org/feed/commercetools-dotnet-core-sdk/package/nuget/commercetools.Sdk.All/1.0.0-alpha-892

By adding the feed sources to your nuget config you could always retrieve the alpha versions.

https://www.myget.org/F/commercetools-dotnet-core-sdk/api/v2
https://www.myget.org/F/commercetools-dotnet-core-sdk/api/v3/index.json

Besides that we will soon release the next RC
