### ISSUE TITLE
Question about Creating a Customer

### ISSUE THREAD

**Issue by glennsdavis** [commercetools/commercetools-dotnet-core-sdk#129]
The code listed below creates customer in commercetools but the customer object is not initialized. This is because the Create Customer method in commertools returns a CustomerSignInResult object and not a Customer object. How do I get the CustomerSignInResult response using the SDK?

CreateCommand<Customer> command = new CreateCommand<Customer>(customerDraft);
**Customer customer** = client.ExecuteAsync(command).Result;

**Comment by MicheleRezk** [comment]
CreateCommand is used for all resources types except Customer, you have to use SignUpCustomerCommand, it will be something like this:

```
var result = (CustomerSignInResult) await _client.ExecuteAsync(
                new SignUpCustomerCommand(customerDraft));
var customer = result.Customer;
```

Also you can use the command builder direct to Create/SignUp new customer, it will like this:
```
var result = (CustomerSignInResult) await _client
                .Builder().Customers().SignUp(customerDraft).ExecuteAsync();
var customer = result.Customer;
```

let me know if this helps.

**Comment by glennsdavis** [comment]
Thank you for your help with this issue.
