### ISSUE TITLE
Override the Correlation ID provider

### ISSUE THREAD

**Issue by carlokok** [commercetools/commercetools-dotnet-core-sdk#130]
How does one override the correlation ID (instead of using the default one) provider?

**Comment by MicheleRezk** [comment]
You can create your own custom ICorrelationIdProvider and inject it in the services container, it will be something like this:
[DefaultCorrelationIdProvider](https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/6846491dbf902f7a4f82e97ad3480b5654a84e04/commercetools.Sdk/commercetools.Sdk.HttpApi/DelegatingHandlers/DefaultCorrelationIdProvider.cs)

Please let me know if you have any question

**Comment by carlokok** [comment]
Yeah that part I figured out. I just can't figure out how to put it inside the container. The current place this is registered is deep inside private methods.

**Comment by jenschude** [comment]
Just as a hint: services.UseCommercetools().AddSingleton(ICorrelationIdProvider, YourCorreletionIdProvider)

This should override the internally registered default provider

**Comment by carlokok** [comment]
So I tried:
```

            var ct = services.UseCommercetools(new ConfigurationWrapper(settings));
            ct.Services.AddSingleton<ICorrelationIdProvider, AppInsightsCorrelationIDHandler>();
```

and 
```

            services.UseCommercetools(new ConfigurationWrapper(settings));
            services.AddSingleton<ICorrelationIdProvider, AppInsightsCorrelationIDHandler>();
```

As the result of UseCommercetools is an IHttpClientBuilder and doesn't seem to have AddSingleton.

**Comment by jenschude** [comment]
Ah sorry then it‘s

services.UseCommercetools;
services.AddSingleton

**Comment by carlokok** [comment]
That's what I tried and doesn't seem to ever create AppInsightsCorrelationIDHandler or call it.

**Comment by MicheleRezk** [comment]
yes you have to configure your custom services before commercetools services, so move this line

`services.AddSingleton<ICorrelationIdProvider, AppInsightsCorrelationIDHandler>();` before UseCommercetools line, so your injected custom service will be retrieved first when it's needed.

Please try it and let me know if this works

**Comment by carlokok** [comment]
not here. But maybe I'm doing something wrong:
```
    public class AppInsightsCorrelationIDHandler : ICorrelationIdProvider
    {
        public AppInsightsCorrelationIDHandler()
        {

        }
        public string CorrelationId => Activity.Current?.Id ?? Guid.NewGuid().ToString();
    }
...

            services.AddSingleton<ICorrelationIdProvider, AppInsightsCorrelationIDHandler>();
            services.UseCommercetools(new ConfigurationWrapper(settings));
```

**Comment by MicheleRezk** [comment]
I just merged the PR which has the fix for this issue, I believe you can now inject your custom correlationProvider service before UseCommercetools

**Comment by carlokok** [comment]
working perfectly! Thanks @MicheleRezk
