### ISSUE TITLE
Parsing complex attributes fails with error

### ISSUE THREAD

**Issue by carlokok** [commercetools/commercetools-dotnet-core-sdk#133]
This is related to  #131 but now for products that use a complex attribute.

I'm getting:

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {"Accessed JArray values with invalid key value: \"key\". Int32 array index expected."} | System.ArgumentException

 	Newtonsoft.Json.dll!Newtonsoft.Json.Linq.JArray.this[object].get(object key)	Unknown
 	commercetools.Sdk.Serialization.dll!commercetools.Sdk.Serialization.LocalizedEnumConverter<commercetools.Sdk.Domain.Products.Attributes.Attribute, commercetools.Sdk.Domain.Products.Attributes.LocalizedEnumValue>.CanConvert(Newtonsoft.Json.Linq.JToken property) Line 21	C#
 	commercetools.Sdk.Serialization.dll!commercetools.Sdk.Serialization.MapperTypeRetriever<commercetools.Sdk.Domain.Products.Attributes.Attribute>.GetTypeForTokenFromMapper(Newtonsoft.Json.Linq.JToken token) Line 26	C#
 	commercetools.Sdk.Serialization.dll!commercetools.Sdk.Serialization.MapperTypeRetriever<commercetools.Sdk.Domain.Products.Attributes.Attribute>.GetTypeForToken(Newtonsoft.Json.Linq.JToken token) Line 19	C#
 	commercetools.Sdk.Serialization.dll!commercetools.Sdk.Serialization.SetMapperTypeRetriever<commercetools.Sdk.Domain.Products.Attributes.Attribute>.GetTypeForToken(Newtonsoft.Json.Linq.JToken token) Line 22	C#
>	commercetools.Sdk.Serialization.dll!commercetools.Sdk.Serialization.AttributeConverter.ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer) Line 37	C#

jsonObject inside AttributeConverter.ReadJson:

```
{
  "name": "printmethod",
  "value": [
    [
      {
        "value": "25 x 10",
        "name": "size"
      },
      {
        "value": "P1",
        "name": "id"
      },
      {
        "value": {
          "nl": "**"
        },
        "name": "name"
      },
      {
        "value": {
          "nl": "Wtte Dop"
        },
        "name": "displaylabel"
      }
    ],
    [
      {
        "value": "25cx",
        "name": "size"
      },
      {
        "value": "P1",
        "name": "id"
      },
      {
        "value": {
          "nl": "Bottle"
        },
        "name": "displaylabel"
      },
      {
        "value": {
          "nl": "pmm"
        },
        "name": "name"
      }
    ]
  ]
}

**Comment by MicheleRezk** [comment]
Can you tell me what the type you want to deseralize the above json to?

**Comment by carlokok** [comment]
It's an attribute that contains a value from this attribute definition: https://github.com/commercetools/commercetools-dotnet-core-sdk/issues/131 . I can give the full document returned if needed (But I can't post that publically)

**Comment by carlokok** [comment]
Here's the stripped input:

```
{
   "limit":20,
   "offset":0,
   "count":1,
   "total":10,
   "results":[
      {
         "lastModifiedAt":"2020-06-16T06:49:09.772Z",
         "createdAt":"2020-06-11T12:24:03.002Z",
         "taxCategory":{
            "typeId":"tax-category",
            "id":"bb27eca5-1335-4e46-961f-47f969014e76"
         },
         "key":"****",
         "published":true,
         "hasStagedChanges":false,
         "searchKeywords":{

         },
         "masterVariant":{
            "attributes":[
               {
                  "name":"primary_cat",
                  "value":{
                     "typeId":"category",
                     "id":"daad4a48-2242-4206-8daa-9eb75b8391b1"
                  }
               },
               {
                  "name":"printMethods",
                  "value":[
                     [
                        {
                           "name":"size",
                           "value":"25 x 10"
                        },
                        {
                           "name":"id",
                           "value":"P1"
                        },
                        {
                           "name":"name",
                           "value":{
                              "nl":"ab"
                           }
                        },
                        {
                           "name":"displaylabel",
                           "value":{
                              "nl":"Wtte Dop"
                           }
                        }
                     ]
                  ]
               }
            ],
            "assets":[

            ],
            "images":[
            ],
            "prices":[

            ],
            "key":"123",
            "sku":"456",
            "id":1
         },
         "metaDescription":{
            "nl":"",
            "de":""
         },
         "metaTitle":{
            "nl":"",
            "de":""
         },
         "slug":{
            "nl":"abddef"
         },
         "categoryOrderHints":{

         },
         "categories":[

         ],
         "description":{
            "nl":"bacdef."
         },
         "name":{
            "nl":"def"
         },
         "productType":{
            "typeId":"product-type",
            "id":"890a08e1-ad70-4a04-9b3a-76eba5eb75b3"
         },
         "version":7,
         "id":"96b5960b-8c08-4ded-a5ca-a7844e975bca"
      }
   ]
}
```

**Comment by MicheleRezk** [comment]
I just merged the PR which has the fix for this issue. Thanks for reporting it

**Comment by jenschude** [comment]
RC2 has been tagged
