### ISSUE TITLE
Attribute.IsMoneyAttribute() returns true for strings

### ISSUE THREAD

**Issue by andersekdahl** [commercetools/commercetools-dotnet-core-sdk#134]
The implementation here:
https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/c362de0db12ed4d269f0977ac72dca30f528ce38/commercetools.Sdk/commercetools.Sdk.Domain/Products/Attributes/AttributeExtensions.cs#L50

returns true for a `Attribute<string>`, I guess that should check for `Attribute<Money>` instead?

**Comment by andersekdahl** [comment]
Seems to be similar problems with the `IsSetXxx()` and `ToSetXxx()`. The attribute I get is of type `Attribute<AttributeSet<Xxx>>` but `IsSetXxx()` checks if the type is of `SetAttribute<Xxx>` which it never is.

**Comment by jenschude** [comment]
Thanks for the hint.

Has already been fixed while working on the other issue about the deserialization of nested attributes.

**Comment by MicheleRezk** [comment]
I just merged the PR which has the fix for this issue. Thanks for reporting it

**Comment by jenschude** [comment]
I just tagged RC2
