### ISSUE TITLE
Getting a customer by email address

### ISSUE THREAD

**Issue by glennsdavis** [commercetools/commercetools-dotnet-core-sdk#138]
I am attempting to get a customer by email address from commercetools using a Query Predicate. The search is case-sensitive. For example if CT contains "Bob@gmail.com" and I pass "bob@gmail.com" then I do not get a result. How to the search to be case-insensitive? See example below. Thank you.

QueryCommand command = new QueryCommand();
QueryPredicate predicate = new QueryPredicate(c => c.Email == email);
command.SetWhere(predicate);
PagedQueryResult response = await _client.ExecuteAsync(command);

**Comment by jenschude** [comment]
There is a special predicate field available called `lowerCaseEmail` which is not in the customer itself. So the workaround could be to use a String predicate till we implemented a LINQ helper for this

`command.SetWhere("lowerCaseEmail = {email}")`

**Comment by glennsdavis** [comment]
Thank you for the quick response. I tried the following and several variations:
string email = "glenn.davis@vizio.com";QueryCommand<Customer> command = new QueryCommand<Customer>();command.SetWhere($"lowerCaseEmail = {email}");PagedQueryResult<Customer> response = client.ExecuteAsync(command).Result;

However, I always get an exception. For example, above code generates the following:

GET https://api.us-central1.gcp.commercetools.com/vizio-dev/customers?where=lowerCaseEmail %3D glenn.davis@vizio.com&withTotal=false 
Malformed parameter: where: Syntax error while parsing 'where'. Invalid input 'g', expected input parameter or primitive value (line 1, column 16): lowerCaseEmail=glenn.davis@vizio.com


   
 On Thursday, August 13, 2020, 01:31:35 AM PDT, Jens Schulze <notifications@github.com> wrote:  
There is a special predicate field available called lowerCaseEmail which is not in the customer itself. So the workaround could be to use a String predicate till we implemented a LINQ helper for this

command.SetWhere("lowerCaseEmail = {email}")

**Comment by jenschude** [comment]
Yeah i updated the comment a little bit to fix some typos ;)

It must be lowercaseEmail and the email has to be put in double quotes

**Comment by glennsdavis** [comment]
Thank you. I had tried enclosing the email in quotes, but did not have case for the field correct. The following works:
command.SetWhere($"lowercaseEmail  = \"{email}\"");

I closed case in GitHub.
    On Thursday, August 13, 2020, 10:24:56 AM PDT, Jens Schulze <notifications@github.com> wrote:  
 
 


Yeah i updated the comment a little bit to fix some typos ;)

It must be lowercaseEmail and the email has to be put in double quotes

**Comment by glennsdavis** [comment]
This issue can be closed. I was able to get customer by using email address following the updated instructions provided by Jens.
