### ISSUE TITLE
Exception getting cart discount

### ISSUE THREAD

**Issue by glennsdavis** [commercetools/commercetools-dotnet-core-sdk#139]
When there is a Cart Discount in commercetools with "Multibuy line items" selected, I get an exception retrieving cart discounts

**Sample Code**

QueryCommand<CartDiscount> command = new QueryCommand<CartDiscount>();
PagedQueryResult<CartDiscount> response = await client.ExecuteAsync(command);

**Exception**

The exception occurs in SDK in ReadJson function in JsonConverterDecoratorTypeRetrieverBase.cs file.

System.AggregateException: One or more errors occurred. (Couldn't get type to deserialize property type)
---> Newtonsoft.Json.JsonSerializationException: Couldn't get type to deserialize property type
   at commercetools.Sdk.Serialization.JsonConverterDecoratorTypeRetrieverBase`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

![CT2](https://user-images.githubusercontent.com/53874454/90091597-af95cc80-dcdb-11ea-9e29-a7eada7b004b.png)
![CT1](https://user-images.githubusercontent.com/53874454/90091602-b0c6f980-dcdb-11ea-8265-2539f2ec49e7.png)
![JsonConverterDecoratorTypeRetrieverBase](https://user-images.githubusercontent.com/53874454/90091752-15825400-dcdc-11ea-8de3-267826847865.png)

**Comment by glennsdavis** [comment]
Is there any estimate on when this bug fix will be in a release build? Thank you

**Comment by jenschude** [comment]
Thanks for the report.

We just issued a new release 1.0.2 which fixed this issue.
