### ISSUE TITLE
upload image for variant

### ISSUE THREAD

**Issue by carlokok** [commercetools/commercetools-dotnet-core-sdk#142]
The api for upload image for product seems to fail with an error; but it doesn't provide a way to pass the variant ID either, so there's no way to pass that information.

**Comment by MicheleRezk** [comment]
You can pass the parameters (VariantId, fileName, ..etc) by setting Parameters prop in the UploadProductImageCommand like this:

 ```
uploadCommand.Parameters = new UploadProductImageParameters
            {
                Variant = 2,
                Staged = false
            };
```

let me know if this solved the issue

**Comment by carlokok** [comment]
This is working perfect. Thanks!
