### ISSUE TITLE
Attribute extension methods are doing equality / type checking incorrectly

### ISSUE THREAD

**Issue by samcackett** [commercetools/commercetools-dotnet-core-sdk#145]
Hi,

There are some helper methods for converting an `Attribute` to a given type in commercetools.Sdk.Domain.Products.Attributes, for example `ToNumberAttribute()`.

These don't actually work as they're using another method (in `AttributeExtensions` class) to check the type, which uses `typeOf` to check the runtime type against the base type and so the check always fails and you get back a null value. 

I think this should be re-written as the following (using `IsNumberAttribute()` as an example):
```
    public static bool IsNumberAttribute(this IAttribute attribute)
    {
      return attribute is Attribute<double>;
    }
```

`is` will correctly recognise the base type and return true, whereas `typeOf` will compare the runtime type against the base type exactly and so fail. 

They have an example of this in the C# docs [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast).

Would be great if someone could verify and fix this. Minor issue, but easy to fix.

Thanks,

Sam

**Comment by jenschude** [comment]
Has been released with 1.0.3

Thanks for the suggestion
