### ISSUE TITLE
Shippingmethods are returned as list but serialized into an PagedQueryResult<ShippingMethod>

### ISSUE THREAD

**Issue by mzwaal** [commercetools/commercetools-dotnet-core-sdk#146]
When I query shipping methods like this

```
            var command = new QueryCommand<ShippingMethod>
            {
                AdditionalParameters = new GetShippingMethodsForCartAdditionalParameters
                {
                    CartId = cartId
                }
            };

            var result = await client.ExecuteAsync(command).Result;
```

I get a serialization error because a list is returned by the Commercetools server but it is serialized in a PagedQueryResult<ShippingMethod> object and that fails. 

Please fix or provide a workaround.

**Comment by jenschude** [comment]
Your command uses a deprecated endpoint. Better use

https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/commercetools.Sdk/commercetools.Sdk.Client/GetShippingMethodsForCartCommand.cs

This one uses the https://docs.commercetools.com/http-api-projects-shippingMethods#get-shippingmethods-for-a-cart endpoint and deserializes correctly.

**Comment by mzwaal** [comment]
Thanks for the quick reaction!

**Comment by mzwaal** [comment]
It does not work unfortunately. I still get the same error when I use GetShippingMethodsForCartCommand.

**Comment by mzwaal** [comment]
This command is also based on a GetMatchingQueryCommand<T> : Command<PagedQueryResult<T>>, IExpandable

**Comment by MicheleRezk** [comment]
Based on documentation here: https://docs.commercetools.com/http-api-projects-shippingMethods#get-shippingmethods-for-a-cart
The response will be PagedQueryResult with the results array of ShippingMethod:

Please check this integration test "GetShippingMethodsForCart" here:
https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/a33d4054c3b4964b24b2b6ff28e5bb3c58d99182/commercetools.Sdk/IntegrationTests/commercetools.Sdk.IntegrationTests/ShippingMethods/ShippingMethodIntegrationTests.cs

**Comment by mzwaal** [comment]
Yes, and the problem is that the commercetools server does not return a paged object but a json array. The json is an array that contains the list of methods and it is not wrapped in a paged result. Therefore it will not serialize and crashes.

**Comment by jenschude** [comment]
But the test does show that it's working. The deprecated endpoint returned an Array. The new one returns a PagedQueryResult.

**Comment by mzwaal** [comment]
Yes, it works now. There was another instance in my code I had to replace. Still a tricky part of the API, perhaps you can throw an invalid operation exception when using it this way with a pointer to the right direction.

**Comment by jenschude** [comment]
It's not that easy. The API returns successfully with a 200. So the SDK deserializes as the Command said to a PagedQueryResult of type ShippingMethod.

Btw the old endpoint had been deprecated as the return typed based on a query parameter and to avoid exactly the issues you were running into.

**Comment by mzwaal** [comment]
It is easy to detect an instance QueryCommand<ShippingMethod>and you can throw an exception at that point because you know it cannot be executed properly down the line.
