### ISSUE TITLE
Making Reference<T>.Obj virtual

### ISSUE THREAD

**Issue by andersekdahl** [commercetools/commercetools-dotnet-core-sdk#148]
We use the CT objects when indexing to an external search engine, and we do dependency tracking in the background. Meaning that if we're indexing a product, and you use `IClient` to load for example a category, we track the dependency between the product and the category. And if the category is changed we re-index the product.

When you load a category from the Category API, the parent category is automatically loaded as well. Meaning that you can do `category.Parent.Obj.Xyz` but we won't be able to detect that you're taking a dependency on the parent.

Would it be possible to make at least the `Obj` property on `Reference` virtual? That would allow us the create a sub class and add dependency tracking if you access that object.

**Comment by jenschude** [comment]
We just changed the Reference obj to virtual and it will be in the next release
