### ISSUE TITLE
QueryCommand with Custom Objects

### ISSUE THREAD

**Issue by andersekdahl** [commercetools/commercetools-dotnet-core-sdk#157]
Hi!
The documentation states that querying on custom objects should be on `/{projectKey}/custom-objects/{container}/` with a `where` parameter. But when you do `new QueryCommand<CustomObject<X>>().Where(q => q.Container == "..." && q.SomethingElse == "...")` that does not generate an HTTP request to `/{projectKey}/custom-objects/{container}/` but instead `/{projectKey}/custom-objects?where=container %3D "..."`.

Is that OK? From an outside perspective it seems like a risk that the where clause on container would be less optimized than including the container in the path. If not OK, how do you use a QueryCommand that includes the container in the path instead?

**Comment by jenschude** [comment]
Try using the https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/commercetools.Sdk/commercetools.Sdk.Client/GetByContainerAndKeyCommand.cs

;)

**Comment by jenschude** [comment]
Forget the comment please. Just realized that you try to query the container. I think it didn't make a big difference as long as the container was given in the query. But we have to add a container query command.
