### ISSUE TITLE
Unable install package for SDK 1.0.4 

### ISSUE THREAD

**Issue by glennsdavis** [commercetools/commercetools-dotnet-core-sdk#160]
I can install 1.0.3 of the SDK in Microsoft Visual Studio Professional 2019, Version 16.8.4, without issue. However, I am not able to install version 1.0.4 as shown below.

PM> Install-Package commercetools.Sdk.All -Version 1.0.4
Install-Package : Invalid character in the given encoding. Line 1, position 1.
At line:1 char:1
+ Install-Package commercetools.Sdk.All -Version 1.0.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by jenschude** [comment]
As I don't use VS it's hard to reproduce the issue. But searching for this error message appears to be an issue of Nuget itself not the package pulled in. Using Rider I can add the package without issues.

**Comment by glennsdavis** [comment]
I was able to successfully import version 1.1.0 and subsequently vision 1.1.1 without issue.
