### ISSUE TITLE
OrderStateTransitionMessage class is missing OldState field

### ISSUE THREAD

**Issue by Vamic** [commercetools/commercetools-dotnet-core-sdk#165]
I noticed that OrderStateTransition messages have an "oldState" field included in the JSON but both the class and CT documentation say there is only the "state" field but the GraphQL schema has it.

**Comment by jenschude** [comment]
I forwarded the request to the appropiate team. Atm we can't add the field to the SDK as it has to be clarified if it has been exposed by intention and if it stays stable.
