### ISSUE TITLE
Null reference exception in BaseMoney operators

### ISSUE THREAD

**Issue by andersekdahl** [commercetools/commercetools-dotnet-core-sdk#181]
**Describe the bug**
The operator overloads for `BaseMoney` does not handle comparing with `null` here:
https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/commercetools.Sdk/commercetools.Sdk.Domain/Common/BaseMoney.cs#L33-L61

**To Reproduce**
Compare a price with null, like `somePrice == null`.

**Expected behavior**
The operator overloads should be able to handle null values.

**Stack information (please complete the following information):**
 - dotnet: Core 3.1
 - SDK: 1.1.2

**Comment by MicheleRezk** [comment]
@andersekdahl We solved it and created a new release with version 1.1.4
