### ISSUE TITLE
Query to products does not resolves attributes correctly

### ISSUE THREAD

**Issue by theburhan** [commercetools/commercetools-dotnet-core-sdk#192]
while trying to fetch products I assume that product attributes and nested attributes defined in product types are automatically resolved/deserialized. However, I get null value

**To Reproduce**
`return (from p in client.Query<Product>().ToList()
              select p).ToList<Product>();`

**Expected behavior**
attribute values should correctly be resolved

**Actual behavior**
```
{
    "masterVariant":{
        "id":1,
        "sku":"somesku",
        "key":"somekey",
        "prices":[],
        "attributes":[
            {
                "name":"attr1",
                "jsonValue":null
            },
            {
                "name":"attr2",
                "jsonValue":null
            }
        ]
    }
}
```

**Stack information:**
 - commercetools.Sdk.All: 1.1.4
 - dotnet 5

**Additional context**
Using the same call directly from the postman resolves the values correctly.

**Comment by jenschude** [comment]
For performance reasons we had to remove the generic jsonValue with 1.0.3 and it will now only return null all the time. See https://github.com/commercetools/commercetools-dotnet-core-sdk/pull/152

but nevertheless Value should hold the correct deserialized attribute

**Comment by theburhan** [comment]
so I am including Product class from the namespace commercetools.Sdk.Domain, shall I switch to a different Nuget package to have the property "Value" instead of "jsonValue" or shall I downgrade the version of  commercetools.Sdk.All. I actually need those attributes in Azure function to calculate some prices.

**Comment by theburhan** [comment]
ok, I have found a way to extract the attributes, as an example below
 ```
var value = (from p in client.Query<Product>().ToList() select p.MasterData.Current.MasterVariant.Attributes.First<Attribute>().ToNumberAttribute().Value).First();```
