### ISSUE TITLE
HighPrecision.FromDecimal Cent amount not respecting currency fraction digits when rounding

### ISSUE THREAD

**Issue by csi-lund** [commercetools/commercetools-dotnet-core-sdk#193]
Hi

automatic cent population and rounding is not respecting the currency fractions.  If I use HighPrecisionMoney.FromDecimal to generate a HighPrecisionMoney amount for say south korean won currency, which has 0 fraction digits and add it to ExternalTotalPrice, it will cause any actions to be rejected due to an incorrect fraction digits error. 

It cannot of course be set to 0 fraction digits since this is the default as stated in the documentation you are forced to set the cent amount explicitly. 

> The number of fraction digits for a specified high precision money. Note that you can't specify a HighPrecisionMoney that has fraction digits less than or equal to what the currency has by default. The maximum amount of fractionDigits that the platform supports is 20. https://docs.commercetools.com/api/types#highprecisionmoney

https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/0ff99f63a7bbce003fd11a680566735c8fdc0ae0/commercetools.Sdk/commercetools.Sdk.Domain/Common/HighPrecisionMoney.cs#L19

It is possible to work around this issue by explicitly setting the cent amount afterwards and rounding correctly.

**Comment by jenschude** [comment]
Has been fixed with 1.2.0

Thanks for the report
