### ISSUE TITLE
Missing field in ExternalTaxRateDraft

### ISSUE THREAD

**Issue by betabandido** [commercetools/commercetools-dotnet-core-sdk#29]
`ExternalTaxRateDraft` has a field named `includedInPrice` in the REST API (see https://docs.commercetools.com/http-api-projects-carts#externaltaxratedraft).

The equivalent object in the .NET core SDK is missing that field (see https://github.com/commercetools/commercetools-dotnet-core-sdk/blob/master/commercetools.Sdk/commercetools.Sdk.Domain/Carts/ExternalTaxRateDraft.cs).

**Comment by MicheleRezk** [comment]
it's solved now.
