### ISSUE TITLE
Sorting by ID does not work when querying Messages.Message

### ISSUE THREAD

**Issue by PepijnK** [commercetools/commercetools-dotnet-core-sdk#64]
Hi,

I'm writing a piece of integration software where we need to pull all changes on Customers and Orders. We need to use the ID into a compound sort statement within the QueryCommand to make the result deterministic, for example (CreatedAt, Name, ID). However I found out that sorting on ID does not work when used as primary sorting key. 
I am using a master build from 4-10-2019
thanks,
pepijn

**Comment by jenschude** [comment]
As you can see here the sort parameter is correctly appended.

https://github.com/commercetools/commercetools-dotnet-core-sdk/commit/a0a5324d994f0d590ae7e3f118572ac52dbc9aa5

The id is a UUID, which is stored as binary data and is also binary sorted. This means you can't rely on it to be sorted by the UUID string representation, but you can rely on the result being sorted deterministic.

**Comment by PepijnK** [comment]
OK thats fine, so sorting works then. Maybe I was mislead by trying to compare stringwise 
(id > {last_id}). This is in the documentation but I can't get it to work as the SDK complaints about it can't do comparison operators on string.

**Comment by jenschude** [comment]
Ah i see. So we have to add an expression visitor for this special use case.

In the meantime you can just use `queryCommand.Where($"id > \"{lastMessage.Id}\"")` as a workaround
