### ISSUE TITLE
Authentication fails on "scope" (vs "projectscope")

### ISSUE THREAD

**Issue by PepijnK** [commercetools/commercetools-dotnet-core-sdk#67]
Hi,

I'm using CommerceTools authentication URL:
`https://auth.sphere.io/oauth/token?grant_type=client_credentials&scope=ManageProject`
With basic authentication.
However when using the SDK and Postman, I get a 400 back: 
```
{
    "statusCode": 400,
    "message": "Malformed parameter: scope: Invalid scope.",
    "errors": [
        {
            "code": "invalid_scope",
            "message": "Malformed parameter: scope: Invalid scope."
        }
    ],
    "error": "invalid_scope",
    "error_description": "Malformed parameter: scope: Invalid scope."
}
```
When performing the query in Postman with _projectscope_ instead of _scope_, I get back a valid response.

**Comment by PepijnK** [comment]
However it works with value `scope=manage_project:<project-key>`

**Comment by jenschude** [comment]
Yes and this is actually how you should authenticate yourself against the API (see https://docs.commercetools.com/http-api-authorization#client-credentials-flow). The SDK just helps a little bit with predefined scopes and adds the project key to the request.

Also this repository is about the SDK not the API itself ;)

**Comment by PepijnK** [comment]
So projectscope and scope are both allowed, I've missed that, but indeed more of an API question
