### ISSUE TITLE
Plans on ditching Newtonsoft.Json in favour of new System.Text.Json serializer

### ISSUE THREAD

**Issue by btastic** [commercetools/commercetools-dotnet-core-sdk#78]
Hello,

are there any plans of ditching Newtonsoft.Json in favour of System.Text.Json serializer? We are currently rewriting our business applications to use .NET Core 3.0. When returning commercetools responses we have problems when serializing commercetools objects, as they are usually JObjects and so on. System.Text.Json has problems with that. When everyone uses System.Text.Json this would not be a problem.

So.. are there any plans on that?

**Comment by jenschude** [comment]
Yes. This is one of the topics to take a look to in the future but there it has not been planned in details so I can't give any time estimation.

But could you go more in detail what exactly is the problem or how to reproduce your issue?

Cause the only binding to NewtonSoft.Json is in the Serialization project which is only referenced in the HttpApi and the SimpleInjector project.

**Comment by jenschude** [comment]
I added a Test for System.Text.Json together with .NET Core 3.0 with PR #79 

As you can see besides a ReferenceConverter and a small bugfix in the domain models it's possible to use Newtonsoft.Json together with System.Text.Json.

In the long run we will add native support for System.Text.Json

**Comment by jenschude** [comment]
I also fixed the old SDK to be able to serialize the models using System.Text.Json. See [PR 108](https://github.com/commercetools/commercetools-dotnet-sdk/pull/108)

Will push the artifact later to NuGet.
