### ISSUE TITLE
Unable to resolve service for type 'IClientConfiguration' while attempting to activate 'ApiExceptionFactory'

### ISSUE THREAD

**Issue by btastic** [commercetools/commercetools-dotnet-core-sdk#82]
Hello,

just fiddling around with the this library and just found the first exception..

![image](https://user-images.githubusercontent.com/6894999/68135264-acd3a300-ff23-11e9-9211-9e9af5c96b22.png)

Just configuring it as per the readme file gives me the following error:

`InvalidOperationException: Unable to resolve service for type 'commercetools.Sdk.HttpApi.IClientConfiguration' while attempting to activate 'commercetools.Sdk.HttpApi.ApiExceptionFactory'.
`

I had a look at the code and it seems that you never register the `IClientConfiguration` as a singleton.

**Comment by jenschude** [comment]
Actually it makes more sense to remove the ApiExceptionFactory from the container, as it's only used in the ErrorHandler and there a direct instance is created.

**Comment by jenschude** [comment]
The problem arose because the Core 3.0 framework validates the service container. We will soon release a fixed version.
