### ISSUE TITLE
Order Get Custom Fields

### ISSUE THREAD

**Issue by jgnatenko** [commercetools/commercetools-dotnet-core-sdk#89]
Hi,

I am trying to use your package in order to work wirh Orders from Merchant Center.

In my VS code I try to work with **custom Fields** like "KupCustomerNumber" or "AbAccountBusinessPartnerId".
Code Example: 
**var resultQuery = await _client.ExecuteAsync(command.Where(c => (string)c.Custom.Fields["KupCustomerNumber"]== "xxxxxx|")):**

**Problem:** while executing the above  code line, the field "**KupCustomerNumber**" will be converted in "**kupCustomerNumber**" (in lower case)! Like that;

**custom(fields(kupCustomerNumber="xxxxxx"))**

Of course, the returned result is null because of name of custom field.

**Comment by jenschude** [comment]
Hi.

We identified the issue in one of the predicate visitors. As a workaround for the time being till it gets released you could always directly use a string like

```
var resultQuery = await _client.ExecuteAsync(command.Where("custom(fields(KupCustomerNumber=\"xxxxxx\"))"):
```
