### ISSUE TITLE
Query Case Sensitive

### ISSUE THREAD

**Issue by jgnatenko** [commercetools/commercetools-dotnet-core-sdk#98]
Hi,
I have a question: 
Is it possible to make a **query case insensitive**?
command.Where("custom(fields(lastName=\"" + exampleName+ "\"))");
And get result for both variants: **e**xampleName and **E**xampleName

**Comment by jenschude** [comment]
It's a limitation by the API itself. The query predicates are always case sensitive.

You could to a query using the `or` operator like: `custom(fields(lastName="exampleName" or lastName = "ExampleName"))`. But this could not catch typos like `Examplename`.

A better solution would be to declare in your custom type a normalized field beside the `lastName` (e.g. `normalizedLastName`), always store the lowercased value there and then query for this field using the lowercased value (`custom(fields(normalizedLastName="examplename"))`)

**Comment by jgnatenko** [comment]
Thanks!

**Comment by jgnatenko** [comment]
@jenschude , with GraphQL API is it possible to make query case insestitive?

**Comment by jenschude** [comment]
The GraphQL API has the same limitations as the REST API.
